-- OutVentura Supabase PostgreSQL Schema
-- Simpan file ini di: supabase/migrations/202605230001_initial_schema.sql
-- Jalankan lewat Supabase SQL Editor atau Supabase CLI.

-- Extension untuk UUID/random helper. Aman di Supabase.
create extension if not exists pgcrypto;

-- Supaya script bisa di-run ulang saat development.
-- Hapus urutan child table dulu.
drop table if exists public.chat_messages cascade;
drop table if exists public.chat_sessions cascade;
drop table if exists public.reviews cascade;
drop table if exists public.wishlist cascade;
drop table if exists public.payments cascade;
drop table if exists public.detail_transaksi cascade;
drop table if exists public.transaksi cascade;
drop table if exists public.alat cascade;
drop table if exists public.pegawai cascade;
drop table if exists public.penyewa cascade;

-- =========================
-- TABLE: penyewa / customer
-- =========================
create table public.penyewa (
  id bigint generated by default as identity primary key,
  nama varchar(100) not null,
  email varchar(150) not null unique,
  password varchar(255) not null,
  telepon varchar(20),
  alamat text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- TABLE: pegawai / admin
-- =========================
create table public.pegawai (
  id bigint generated by default as identity primary key,
  nama varchar(100) not null,
  email varchar(150) not null unique,
  password varchar(255) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- TABLE: alat / rental items
-- =========================
create table public.alat (
  id bigint generated by default as identity primary key,
  nama_alat varchar(100) not null,
  kategori varchar(50) not null,
  harga integer not null check (harga >= 0),
  stok integer not null default 0 check (stok >= 0),
  deskripsi text,
  gambar text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- TABLE: transaksi / rental transaction
-- Status lama dipertahankan agar cocok dengan kode sekarang:
-- pending, lunas, selesai, batal
-- Status payment/rental disiapkan untuk pengembangan berikutnya:
-- pending_payment, paid, dipinjam, expired
-- =========================
create table public.transaksi (
  id bigint generated by default as identity primary key,
  id_penyewa bigint not null references public.penyewa(id) on update cascade on delete restrict,
  id_pegawai bigint references public.pegawai(id) on update cascade on delete set null,
  tanggal_transaksi date not null default current_date,
  tanggal_mulai date not null,
  tanggal_selesai date not null,
  jumlah_hari integer generated always as (tanggal_selesai - tanggal_mulai) stored,
  total_harga integer not null default 0 check (total_harga >= 0),
  status varchar(30) not null default 'pending' check (
    status in (
      'pending',
      'lunas',
      'selesai',
      'batal',
      'pending_payment',
      'paid',
      'dipinjam',
      'expired'
    )
  ),

  -- Kolom opsional untuk integrasi payment gateway seperti Midtrans nanti.
  payment_order_id varchar(100) unique,
  payment_token text,
  payment_redirect_url text,
  payment_method varchar(50),
  paid_at timestamptz,

  -- Kolom opsional untuk fitur pengembalian dan denda.
  tanggal_kembali date,
  denda integer not null default 0 check (denda >= 0),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint transaksi_tanggal_valid check (tanggal_selesai > tanggal_mulai)
);

-- =========================
-- TABLE: detail_transaksi
-- =========================
create table public.detail_transaksi (
  id bigint generated by default as identity primary key,
  id_transaksi bigint not null references public.transaksi(id) on update cascade on delete cascade,
  id_alat bigint not null references public.alat(id) on update cascade on delete restrict,
  jumlah integer not null check (jumlah > 0),
  harga_satuan integer not null check (harga_satuan >= 0),
  subtotal integer not null check (subtotal >= 0),
  created_at timestamptz not null default now()
);

-- =========================
-- TABLE: payments
-- Opsional untuk histori payment gateway.
-- =========================
create table public.payments (
  id bigint generated by default as identity primary key,
  id_transaksi bigint not null references public.transaksi(id) on update cascade on delete cascade,
  provider varchar(50) not null default 'midtrans',
  order_id varchar(100) not null unique,
  transaction_id varchar(100),
  gross_amount integer not null check (gross_amount >= 0),
  payment_type varchar(50),
  transaction_status varchar(50) not null default 'pending',
  fraud_status varchar(50),
  raw_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- TABLE: wishlist
-- Opsional untuk fitur favorit alat.
-- =========================
create table public.wishlist (
  id bigint generated by default as identity primary key,
  id_penyewa bigint not null references public.penyewa(id) on update cascade on delete cascade,
  id_alat bigint not null references public.alat(id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  unique (id_penyewa, id_alat)
);

-- =========================
-- TABLE: reviews
-- Opsional untuk fitur rating setelah sewa selesai.
-- =========================
create table public.reviews (
  id bigint generated by default as identity primary key,
  id_penyewa bigint not null references public.penyewa(id) on update cascade on delete cascade,
  id_alat bigint not null references public.alat(id) on update cascade on delete cascade,
  id_transaksi bigint references public.transaksi(id) on update cascade on delete set null,
  rating integer not null check (rating between 1 and 5),
  komentar text,
  created_at timestamptz not null default now(),
  unique (id_penyewa, id_alat, id_transaksi)
);

-- =========================
-- TABLE: chat_sessions & chat_messages
-- Opsional untuk chatbot AI.
-- =========================
create table public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  id_penyewa bigint references public.penyewa(id) on update cascade on delete set null,
  title varchar(150),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chat_messages (
  id bigint generated by default as identity primary key,
  id_session uuid not null references public.chat_sessions(id) on update cascade on delete cascade,
  role varchar(20) not null check (role in ('user', 'assistant', 'system')),
  message text not null,
  metadata jsonb,
  created_at timestamptz not null default now()
);

-- =========================
-- Index untuk performa query
-- =========================
create index idx_alat_kategori on public.alat(kategori);
create index idx_alat_nama on public.alat(nama_alat);

create index idx_transaksi_penyewa on public.transaksi(id_penyewa);
create index idx_transaksi_status on public.transaksi(status);
create index idx_transaksi_tanggal_sewa on public.transaksi(tanggal_mulai, tanggal_selesai);
create index idx_transaksi_payment_order_id on public.transaksi(payment_order_id);

create index idx_detail_transaksi_transaksi on public.detail_transaksi(id_transaksi);
create index idx_detail_transaksi_alat on public.detail_transaksi(id_alat);

create index idx_payments_transaksi on public.payments(id_transaksi);
create index idx_payments_order_id on public.payments(order_id);

create index idx_reviews_alat on public.reviews(id_alat);
create index idx_wishlist_penyewa on public.wishlist(id_penyewa);
create index idx_chat_messages_session on public.chat_messages(id_session);

-- =========================
-- Trigger updated_at otomatis
-- =========================
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_penyewa_updated_at
before update on public.penyewa
for each row execute function public.set_updated_at();

create trigger set_pegawai_updated_at
before update on public.pegawai
for each row execute function public.set_updated_at();

create trigger set_alat_updated_at
before update on public.alat
for each row execute function public.set_updated_at();

create trigger set_transaksi_updated_at
before update on public.transaksi
for each row execute function public.set_updated_at();

create trigger set_payments_updated_at
before update on public.payments
for each row execute function public.set_updated_at();

create trigger set_chat_sessions_updated_at
before update on public.chat_sessions
for each row execute function public.set_updated_at();

-- =========================
-- View untuk riwayat transaksi mirip query MySQL GROUP_CONCAT
-- =========================
create or replace view public.vw_riwayat_transaksi as
select
  t.*,
  string_agg(a.nama_alat, ', ' order by a.nama_alat) as nama_alat_list
from public.transaksi t
left join public.detail_transaksi dt on dt.id_transaksi = t.id
left join public.alat a on a.id = dt.id_alat
group by t.id;

-- =========================
-- View dashboard laporan bulanan
-- =========================
create or replace view public.vw_laporan_bulanan as
select
  extract(year from tanggal_transaksi)::int as tahun,
  extract(month from tanggal_transaksi)::int as bulan,
  count(*)::int as total_transaksi,
  coalesce(sum(total_harga), 0)::int as total_pendapatan,
  count(*) filter (where status = 'selesai')::int as selesai,
  count(*) filter (where status in ('pending', 'pending_payment'))::int as pending,
  count(*) filter (where status in ('lunas', 'paid'))::int as lunas,
  count(*) filter (where status = 'batal')::int as batal
from public.transaksi
group by extract(year from tanggal_transaksi), extract(month from tanggal_transaksi);

-- =========================
-- Function cek jumlah alat yang sedang terbooking pada rentang tanggal tertentu
-- Bisa dipakai backend untuk validasi stok rental.
-- =========================
create or replace function public.get_booked_quantity(
  p_id_alat bigint,
  p_tanggal_mulai date,
  p_tanggal_selesai date
)
returns integer
language sql
stable
as $$
  select coalesce(sum(dt.jumlah), 0)::int
  from public.detail_transaksi dt
  join public.transaksi t on t.id = dt.id_transaksi
  where dt.id_alat = p_id_alat
    and t.status in ('pending', 'lunas', 'pending_payment', 'paid', 'dipinjam')
    and t.tanggal_mulai < p_tanggal_selesai
    and t.tanggal_selesai > p_tanggal_mulai;
$$;

-- =========================
-- RLS Supabase
-- Untuk sementara diaktifkan supaya aman kalau nanti pakai Supabase API langsung.
-- Kalau akses database lewat backend Express memakai DB password/service role, backend tetap bisa mengakses.
-- =========================
alter table public.penyewa enable row level security;
alter table public.pegawai enable row level security;
alter table public.alat enable row level security;
alter table public.transaksi enable row level security;
alter table public.detail_transaksi enable row level security;
alter table public.payments enable row level security;
alter table public.wishlist enable row level security;
alter table public.reviews enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
